### PR TITLE
Retry limit

### LINKED ISSUE #100: Retry-on-error during indexation never gives up
When `retryOnError` is true and an error occurs during sync/indexation, the plugin will retry to index the transactions that failed to be indexed in Elasticsearch.
If, for some unforeseen reason, retrying does not solve the issue (e.g. disk is full, document is malformed, etc.), the plugin enters an infinite retry-loop.
There should be a way to allow the plugin to give up after a certain number of retries.

### PR DESCRIPTION
**Pull request by davidrapin**
Fixes #100

### CODE REVIEW

File: src/main/java/com/graphaware/module/es/ElasticSearchWriter.java [hunk 1]
```diff
@@ -124,19 +126,44 @@ protected void processOperations(List<Collection<WriteOperation<?>>> operationGr
...
+        if (allFailed.isEmpty()) {
+            consecutiveErrors = 0;
+            return;
+        }
+
+        // error, count consecutive errors
+        consecutiveErrors++;
+
+        // no retry-on-error, log and give up
+        if (!retryOnError) {
```
Comment (ikwattro) [inline src/main/java/com/graphaware/module/es/ElasticSearchWriter.java]: This can go before incrementing the counter.

File: src/main/java/com/graphaware/module/es/ElasticSearchWriter.java [hunk 2]
```diff
@@ -124,19 +126,44 @@ protected void processOperations(List<Collection<WriteOperation<?>>> operationGr
...
+            LOG.warn(allFailed.size() + " operations could not be replicated to Elasticsearch. These updates got lost.");
+            return;
+        }
+
+        // retry-on-error enabled but maximum consecutive errors reached: give up and reset counter
+        if (consecutiveErrors > MAXIMUM_CONSECUTIVE_ERRORS) {
+            LOG.warn("" +
+                    allFailed.size() + " operations could not be replicated to Elasticsearch. " +
+                    "Giving up after " + MAXIMUM_CONSECUTIVE_ERRORS + " consecutive errors. " +
```
Comment (ikwattro) [inline src/main/java/com/graphaware/module/es/ElasticSearchWriter.java]: Would change to "giving up after XX retries" instead of errors.

File: src/main/java/com/graphaware/module/es/ElasticSearchWriter.java [hunk 3]
```diff
@@ -40,10 +40,12 @@
  * A {@link ThirdPartyWriter} to Elasticsearch (https://www.elastic.co/).
  */
 public class ElasticSearchWriter extends BaseThirdPartyWriter {
+    public static final int MAXIMUM_CONSECUTIVE_ERRORS = 50;
```
Comment (ikwattro) [inline src/main/java/com/graphaware/module/es/ElasticSearchWriter.java]: Make this much smaller please, like 5. And add a configuration option for increasing it.

**Comment by davidrapin** [comment]
@ikwattro requested changes have been done, sorry for the delay ;)
